baseurl = "https://dpfrakes.dev/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Dan Frakes"
title = "Dan Frakes"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Dan Frakes' personal blog"
copyright = "Copyright © 2019 Dan Frakes"
logofile = ""
# logofile = "img/kerr-empty.png"
faviconfile = "img/favicon.png"
highlightjs = true
progressively = true
extracssfiles = ["css/override.css"]
extrajsfiles = ["js/main.js"]
align_left = false
lang = "en"
github = "dpfrakes"
email = ""
linkedin = "dpfrakes"
# twitter = "dpfrakes"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false

# disablefancyfonts = true
